You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Internal Server Error: /api/professional-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 439, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 106, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProfessionalInformation' object has no attribute 'work_experience'. Did you mean: 'work_experiences'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 148, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 472, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `work_experience` on serializer `ProfessionalInformationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ProfessionalInformation` instance.
Original exception text was: 'ProfessionalInformation' object has no attribute 'work_experience'.
"GET /api/professional-info/ HTTP/1.1" 500 136633
Internal Server Error: /api/professional-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 439, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 106, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProfessionalInformation' object has no attribute 'work_experience'. Did you mean: 'work_experiences'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 148, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\fields.py", line 472, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `work_experience` on serializer `ProfessionalInformationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `ProfessionalInformation` instance.
Original exception text was: 'ProfessionalInformation' object has no attribute 'work_experience'.
"GET /api/professional-info/ HTTP/1.1" 500 136633
Internal Server Error: /api/professional-info/2/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 191, in update
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 186, in get_object
    raise Http404("Professional Information not found")
          ^^^^^^^
NameError: name 'Http404' is not defined
"PUT /api/professional-info/2/ HTTP/1.1" 500 99587
Internal Server Error: /admin/suresh/swotanalysis/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'get_strengths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SwotAnalysis has no field named 'get_strengths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\templatetags\admin_list.py", line 345, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in __init__
    super().__init__(*items)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\contrib\admin\utils.py", line 298, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\admin.py", line 207, in get_strengths
    return obj.strengths[:50] if obj.strengths else 'N/A'  # Truncate to 50 characters for display
           ~~~~~~~~~~~~~^^^^^
TypeError: 'RelatedManager' object is not subscriptable
"GET /admin/suresh/swotanalysis/ HTTP/1.1" 500 392652
Internal Server Error: /api/strengths/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 470, in perform_create
    swot_analysis, _ = SwotAnalysis.objects.get_or_create(user=self.request.user)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
suresh.models.SwotAnalysis.MultipleObjectsReturned: get() returned more than one SwotAnalysis -- it returned 2!
"POST /api/strengths/ HTTP/1.1" 500 113436
Internal Server Error: /api/weaknesses/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 481, in perform_create
    swot_analysis, _ = SwotAnalysis.objects.get_or_create(user=self.request.user)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
suresh.models.SwotAnalysis.MultipleObjectsReturned: get() returned more than one SwotAnalysis -- it returned 2!
"POST /api/weaknesses/ HTTP/1.1" 500 113454
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 145
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 145
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 145
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 145
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149241
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149241
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/global-info/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `nationality` is not valid for model `GlobalInformation` in `suresh.serializers.GlobalInformationSerializer`.
"GET /api/global-info/ HTTP/1.1" 500 149546
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 99495
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 99081
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\New folder\sureshproject\suresh\views.py", line 78, in create
    email=user.email,
          ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
"POST /api/register/ HTTP/1.1" 500 99075
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Humma\AppData\Roaming\Python\Python312\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
